name: "HCL AppScan SAST for ASoC EU Instance"
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@ASPL-2090
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 4b489cb2-ae9f-4aea-8079-9e37099ce87a
          service_url: ${{secrets.SERVICE_URL}}
          scan_info_hyperlinks: false
          wait_for_analysis: false
