name: "HCL AppScan SAST"
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@3153cfb62e24c1ef4c906412aac7f868c83576c6
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 605d486f-3dba-40ba-a565-638a2ffe93f7
          service_url: https://blmycldtl446131.appscan-test.local
          wait_for_analysis: true
          static_analysis_only: true
          acceptssl: true
