name: "HCL AppScan SAST"
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@ASA-13165
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 1dd70de0-f756-4cd4-bad3-8354731ceff4
          acceptssl: ${{secrets.ACCEPTSSL}}
          service_url: ${{secrets.SERVICE_URL}}
          sast_scan_id: 5a221bd3-4d42-4e53-bf2b-36690c7697ff
