name: "HCL AppScan SAST for AS360"
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@main
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 1dd70de0-f756-4cd4-bad3-8354731ceff4
          acceptssl: true
          service_url: https://blmycldtl446131.nonprod.hclpnp.com
          wait_for_analysis: true
          static_analysis_only: true
                   
     # Upload PR HTML report
      - name: Upload PR report
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: appscan-pr-report
          path: | 
            Report_*.html
          if-no-files-found: ignore

      # Upload build summary HTML report
      - name: Upload Build report
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: appscan-build-report
          path: | 
             Report_*.html
          if-no-files-found: ignore
