name: "HCL AppScan SAST"
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@ASA-13165
        with:
          asoc_key: ${{secrets.ASOC_KEY}}          
          application_id: 1dd70de0-f756-4cd4-bad3-8354731ceff4
          acceptssl: ${{secrets.ACCEPTSSL}}
          service_url: ${{secrets.SERVICE_URL}}
          static_analysis_only: true
          wait_for_analysis: true
