name: "HCL AppScan SAST for ASoC"
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.9
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 21b194f5-cea5-4ff6-a4d1-a03103a3e2fb
